name: Check builds for pull requests

on:
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: xt0rted/markdownlint-problem-matcher@v3
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Install node modules
        run: yarn
      - name: Lint markdown files
        run: yarn lint:md
      - name: Lint with prettier
        id: prettier
        run: yarn lint:prettier
      - name: Show prettier problems
        if: ${{ failure() && steps.prettier.conclusion == 'failure' }}
        run: |
          yarn lint-fix:prettier
          git diff
      - name: Check for non-breaking spaces
        run: |
          ./.github/check_nbsp.sh content/ 5

  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.146.5
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build with Hugo
        run: |
          hugo mod get -u
          hugo --logLevel debug
